Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,4 +39,11 @@ jobs:
           
       - name: Check the result
         run: |
-          echo "Hello World!"
+          echo "Prediction: ${{ steps.predict-build-error.outputs.prediction }}"
+          echo "Probability: ${{ steps.predict-build-error.outputs.probability }}"
+          if [[ "${{ steps.predict-build-error.outputs.prediction }}" == "error" ]]; then
+            echo "Build error predicted!"
+            exit 1
+          else
+            echo "Build predicted as successful!"
+          fi
